apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.postgresql
  version: v1
  initTimeout: 60s
  metadata:
    - name: connectionString
      secretKeyRef:
        name: todo-secrets
        key: DAPR_DATABASE_URL
    - name: tableName
      value: "dapr_state"
    - name: metadataTableName
      value: "dapr_metadata"
    - name: timeout
      value: "30"
auth:
  secretStore: kubernetes-secrets
scopes:
  - backend
